ADVANCED RUL PREDICTION: Gated Ensemble BiLSTM + Attention (Optimized)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Pre-processing

In [ ]:
import numpy as np
import pandas as pd

from IPython.display import display, HTML
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots
import plotly.io as pio


import seaborn as sns
from importlib import reload
import matplotlib.pyplot as plt
import matplotlib
import warnings

# Configure Jupyter Notebook
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 500)
pd.set_option('display.expand_frame_repr', False)
# pd.set_option('max_colwidth', -1)
display(HTML("<style>div.output_scroll { height: 35em; }</style>"))

reload(plt)
%matplotlib inline
%config InlineBackend.figure_format ='retina'

warnings.filterwarnings('ignore')

# configure plotly graph objects
pio.renderers.default = 'iframe'
# pio.renderers.default = 'vscode'

pio.templates["ck_template"] = go.layout.Template(
    layout_colorway = px.colors.sequential.Viridis,
#     layout_hovermode = 'closest',
#     layout_hoverdistance = -1,
    layout_autosize=False,
    layout_width=800,
    layout_height=600,
    layout_font = dict(family="Calibri Light"),
    layout_title_font = dict(family="Calibri"),
    layout_hoverlabel_font = dict(family="Calibri Light"),
#     plot_bgcolor="white",
)

# pio.templates.default = 'seaborn+ck_template+gridon'
pio.templates.default = 'ck_template+gridon'
# pio.templates.default = 'seaborn+gridon'
# pio.templates

In [ ]:
index_names = ['engine', 'cycle']
setting_names = ['setting_1', 'setting_2', 'setting_3']
sensor_names=[ "(Fan inlet temperature) (◦R)",
"(LPC outlet temperature) (◦R)",
"(HPC outlet temperature) (◦R)",
"(LPT outlet temperature) (◦R)",
"(Fan inlet Pressure) (psia)",
"(bypass-duct pressure) (psia)",
"(HPC outlet pressure) (psia)",
"(Physical fan speed) (rpm)",
"(Physical core speed) (rpm)",
"(Engine pressure ratio(P50/P2)",
"(HPC outlet Static pressure) (psia)",
"(Ratio of fuel flow to Ps30) (pps/psia)",
"(Corrected fan speed) (rpm)",
"(Corrected core speed) (rpm)",
"(Bypass Ratio) ",
"(Burner fuel-air ratio)",
"(Bleed Enthalpy)",
"(Required fan speed)",
"(Required fan conversion speed)",
"(High-pressure turbines Cool air flow)",
"(Low-pressure turbines Cool air flow)" ]
col_names = index_names + setting_names + sensor_names

In [ ]:
df_train = pd.read_csv('drive/MyDrive/CMaps/train_FD004.txt',sep=r'\s+',header=None,index_col=False,names=col_names)
df_test = pd.read_csv('drive/MyDrive/CMaps/test_FD004.txt',sep=r'\s+',header=None,index_col=False,names=col_names)
df_test_RUL = pd.read_csv('drive/MyDrive/CMaps/RUL_FD004.txt',sep=r'\s+',header=None,index_col=False,names=['RUL'])

In [ ]:

# corr = df_train.corr()
# mask = np.triu(np.ones_like(corr, dtype=bool))

# f, ax = plt.subplots(figsize=(20, 20))
# cmap = sns.diverging_palette(230, 10, as_cmap=True)

# # Draw the heatmap with annotation
# sns.heatmap(
#     corr,
#     mask=mask,
#     cmap=cmap,
#     vmax=.3,
#     center=0,
#     square=True,
#     linewidths=.5,
#     cbar_kws={"shrink": .5},
#     annot=True,           # <- Add this line
#     fmt=".1f"             # <- Format the numbers to 2 decimal places
# )

# plt.show()

In [ ]:
# sens_const_values = []
# for feature in list(setting_names + sensor_names):
#     try:
#         if df_train[feature].min()==df_train[feature].max():
#             sens_const_values.append(feature)
#     except:
#         pass

# print(sens_const_values)
# df_train.drop(sens_const_values,axis=1,inplace=True)
# df_test.drop(sens_const_values,axis=1,inplace=True)

In [ ]:
# cor_matrix = df_train.corr().abs()
# upper_tri = cor_matrix.where(np.triu(np.ones(cor_matrix.shape),k=1).astype(np.bool))
# corr_features = [column for column in upper_tri.columns if any(upper_tri[column] > 0.95)]
# print(corr_features)
# df_train.drop(corr_features,axis=1,inplace=True)
# df_test.drop(corr_features,axis=1,inplace=True)

In [ ]:
features = list(df_train.columns)

In [ ]:
# check for missing data
for feature in features:
    print(feature + " - " + str(len(df_train[df_train[feature].isna()])))

engine - 0
cycle - 0
setting_1 - 0
setting_2 - 0
setting_3 - 0
(Fan inlet temperature) (◦R) - 0
(LPC outlet temperature) (◦R) - 0
(HPC outlet temperature) (◦R) - 0
(LPT outlet temperature) (◦R) - 0
(Fan inlet Pressure) (psia) - 0
(bypass-duct pressure) (psia) - 0
(HPC outlet pressure) (psia) - 0
(Physical fan speed) (rpm) - 0
(Physical core speed) (rpm) - 0
(Engine pressure ratio(P50/P2) - 0
(HPC outlet Static pressure) (psia) - 0
(Ratio of fuel flow to Ps30) (pps/psia) - 0
(Corrected fan speed) (rpm) - 0
(Corrected core speed) (rpm) - 0
(Bypass Ratio)  - 0
(Burner fuel-air ratio) - 0
(Bleed Enthalpy) - 0
(Required fan speed) - 0
(Required fan conversion speed) - 0
(High-pressure turbines Cool air flow) - 0
(Low-pressure turbines Cool air flow) - 0

In [ ]:
# define the maximum life of each engine, as this could be used to obtain the RUL at each point in time of the engine's life
df_train_RUL = df_train.groupby(['engine']).agg({'cycle':'max'})
df_train_RUL.rename(columns={'cycle':'life'},inplace=True)
df_train_RUL.head()

        life
engine
1        321
2        299
3        307
4        274
5        193

In [ ]:
df_train=df_train.merge(df_train_RUL,how='left',on=['engine'])

In [ ]:
df_train['RUL']=df_train['life']-df_train['cycle']
df_train.drop(['life'],axis=1,inplace=True)

# the RUL prediction is only useful nearer to the end of the engine's life, therefore we put an upper limit on the RUL
# this is a bit sneaky, since it supposes that the test set has RULs of less than this value, the closer you are
# to the true value, the more accurate the model will be
df_train['RUL'][df_train['RUL']>125]=125
df_train.head()

   engine  cycle  setting_1  setting_2  setting_3  (Fan inlet temperature) (◦R)  (LPC outlet temperature) (◦R)  (HPC outlet temperature) (◦R)  (LPT outlet temperature) (◦R)  (Fan inlet Pressure) (psia)  (bypass-duct pressure) (psia)  (HPC outlet pressure) (psia)  (Physical fan speed) (rpm)  (Physical core speed) (rpm)  (Engine pressure ratio(P50/P2)  (HPC outlet Static pressure) (psia)  (Ratio of fuel flow to Ps30) (pps/psia)  (Corrected fan speed) (rpm)  (Corrected core speed) (rpm)  (Bypass Ratio)   (Burner fuel-air ratio)  (Bleed Enthalpy)  (Required fan speed)  (Required fan conversion speed)  (High-pressure turbines Cool air flow)  (Low-pressure turbines Cool air flow)  RUL
0       1      1    42.0049     0.8400      100.0                        445.00                         549.68                        1343.43                        1112.93                         3.91                           5.70                        137.36                     2211.86                      8311.32                            1.01                                41.69                                   129.78                      2387.99                       8074.83           9.3335                     0.02               330                  2212                           100.00                                   10.62                                 6.3670  125
1       1      2    20.0020     0.7002      100.0                        491.19                         606.07                        1477.61                        1237.50                         9.35                          13.61                        332.10                     2323.66                      8713.60                            1.07                                43.94                                   312.59                      2387.73                       8046.13           9.1913                     0.02               361                  2324                           100.00                                   24.37                                14.6552  125
2       1      3    42.0038     0.8409      100.0                        445.00                         548.95                        1343.12                        1117.05                         3.91                           5.69                        138.18                     2211.92                      8306.69                            1.01                                41.66                                   129.62                      2387.97                       8066.62           9.4007                     0.02               329                  2212                           100.00                                   10.48                                 6.4213  125
3       1      4    42.0000     0.8400      100.0                        445.00                         548.70                        1341.24                        1118.03                         3.91                           5.70                        137.98                     2211.88                      8312.35                            1.02                                41.68                                   129.80                      2388.02                       8076.05           9.3369                     0.02               328                  2212                           100.00                                   10.54                                 6.4176  125
4       1      5    25.0063     0.6207       60.0                        462.54                         536.10                        1255.23                        1033.59                         7.05                           9.00                        174.82                     1915.22                      7994.94                            0.93                                36.48                                   164.11                      2028.08                       7865.80          10.8366                     0.02               305                  1915                            84.93                                   14.03                                 8.6754  125

In [ ]:
def create_sequences(df, window_size, stride, engine_col='engine'):
    sequences, targets, engine_ids = [], [], []

    for engine_id in df[engine_col].unique():
        engine_data = df[df[engine_col] == engine_id].sort_values('cycle')
        feature_cols = [col for col in engine_data.columns if col not in ['engine', 'cycle', 'RUL']]

        values = engine_data[feature_cols].values
        rul_values = engine_data['RUL'].values

        for i in range(0, len(values) - window_size + 1, stride):
            sequences.append(values[i:i + window_size])
            targets.append(rul_values[i + window_size - 1])
            engine_ids.append(engine_id)

    return np.array(sequences), np.array(targets), np.array(engine_ids)

# Scale features
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
feature_cols = [col for col in df_train.columns if col not in ['engine', 'cycle', 'RUL']]
df_train[feature_cols] = scaler.fit_transform(df_train[feature_cols])
df_test[feature_cols] = scaler.transform(df_test[feature_cols])

In [ ]:
pip install tensorflow

Requirement already satisfied: tensorflow in /usr/local/lib/python3.12/dist-packages (2.19.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from tensorflow) (26.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (5.29.6)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.32.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from tensorflow) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.1.1)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.78.0)
Requirement already satisfied: tensorboard~=2.19.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.19.0)
Requirement already satisfied: keras>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.10.0)
Requirement already satisfied: numpy<2.2.0,>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.0.2)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.15.1)
Requirement already satisfied: ml-dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.5.4)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from astunparse>=1.6.0->tensorflow) (0.46.3)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (0.18.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2026.1.4)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.10.2)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.1.5)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from werkzeug>=1.0.1->tensorboard~=2.19.0->tensorflow) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow) (0.1.2)

In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GroupKFold
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import tensorflow as tf
from tensorflow.keras import layers, models, callbacks, regularizers
from tensorflow.keras.optimizers import Adam
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [ ]:
np.random.seed(42)
tf.random.set_seed(42)

In [ ]:
# ============================================================
# ADVANCED RUL PREDICTION: Gated Ensemble BiLSTM + Attention (Optimized)
# ============================================================

import tensorflow as tf
from tensorflow.keras import layers, models, regularizers, callbacks, optimizers
import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Set random seeds for reproducibility
np.random.seed(42)
tf.random.set_seed(42)

# MODIFIED create_sequences function to handle missing 'RUL' column for test set
def create_sequences(df, window_size, stride, engine_col='engine'):
    sequences, targets, engine_ids = [], [], []

    # Check if 'RUL' column exists in the DataFrame
    has_rul = 'RUL' in df.columns

    for engine_id in df[engine_col].unique():
        engine_data = df[df[engine_col] == engine_id].sort_values('cycle')
        feature_cols = [col for col in engine_data.columns if col not in ['engine', 'cycle', 'RUL']]

        values = engine_data[feature_cols].values

        if has_rul:
            rul_values = engine_data['RUL'].values
        else:
            # If RUL column is not present (e.g., for test data), create a dummy array.
            # These 'targets' will be discarded for X_test anyway.
            rul_values = np.array([])

        # Ensure there are enough data points for the window
        if len(values) < window_size:
            continue # Skip engines that are too short for a single sequence

        for i in range(0, len(values) - window_size + 1, stride):
            sequences.append(values[i:i + window_size])
            if has_rul: # Only append RUL target if RUL column exists
                targets.append(rul_values[i + window_size - 1])
            engine_ids.append(engine_id)

    return np.array(sequences), np.array(targets), np.array(engine_ids)


CONFIG = {
    'WINDOW_SIZE': 60,
    'STRIDE': 2,
    'LSTM_UNITS': [128, 64],
    'DENSE_UNITS': 80,
    'DROPOUT_RATE': 0.3,
    'L2_REG': 0.001,
    'BATCH_SIZE': 32,
    'EPOCHS': 200,
    'LEARNING_RATE': 0.0005,
    'PATIENCE': 35,
    'N_SPLITS': 5
}

print("\nOptimized Configuration:")
for k, v in CONFIG.items():
    print(f"  {k}: {v}")


X_train, y_train, train_engine_ids = create_sequences(
    df_train, CONFIG['WINDOW_SIZE'], CONFIG['STRIDE']
)
X_test, _, test_engine_ids = create_sequences(
    df_test, CONFIG['WINDOW_SIZE'], CONFIG['STRIDE']
)

print(f"Training sequences: {X_train.shape}")
print(f"Test sequences: {X_test.shape}")


# ============================================================
# Custom Layers
# ============================================================

class GatingLayer(layers.Layer):
    def __init__(self, num_branches, **kwargs):
        super(GatingLayer, self).__init__(**kwargs)
        self.num_branches = num_branches

    def build(self, input_shape):
        self.gate_weights = self.add_weight(
            shape=(input_shape[0][-1], self.num_branches),
            initializer='glorot_uniform',
            trainable=True
        )
        self.gate_bias = self.add_weight(
            shape=(self.num_branches,),
            initializer='zeros',
            trainable=True
        )

    def call(self, inputs):
        input_stats = tf.reduce_mean(inputs[0], axis=1)
        gate_scores = tf.nn.softmax(tf.matmul(input_stats, self.gate_weights) + self.gate_bias, axis=-1)
        gate_scores = tf.expand_dims(tf.expand_dims(gate_scores, 1), -1)
        stacked = tf.stack(inputs, axis=2)
        gated = stacked * gate_scores
        fused = tf.reduce_sum(gated, axis=2)
        return fused


class AttentionLayer(layers.Layer):
    """Attention mechanism to highlight critical timesteps after fusion."""
    def __init__(self, **kwargs):
        super(AttentionLayer, self).__init__(**kwargs)

    def build(self, input_shape):
        self.W = self.add_weight(shape=(input_shape[-1], input_shape[-1]),
                                 initializer="glorot_uniform", trainable=True)
        self.b = self.add_weight(shape=(input_shape[-1],),
                                 initializer="zeros", trainable=True)
        self.u = self.add_weight(shape=(input_shape[-1],),
                                 initializer="glorot_uniform", trainable=True)

    def call(self, x):
        u_t = tf.tanh(tf.tensordot(x, self.W, axes=1) + self.b)
        attn_scores = tf.nn.softmax(tf.tensordot(u_t, self.u, axes=1), axis=1)
        attn_scores = tf.expand_dims(attn_scores, -1)
        context = tf.reduce_sum(x * attn_scores, axis=1)
        return context


# ============================================================
# Optimized Gated BiLSTM + Attention Model
# ============================================================

def build_gated_attention_bilstm(input_shape, config):
    inputs = layers.Input(shape=input_shape, name='input')

    # Parallel branches: LSTM, GRU, CNN
    branch_lstm = layers.LSTM(64, return_sequences=True,
                              kernel_regularizer=regularizers.l2(config['L2_REG']))(inputs)
    branch_lstm = layers.LayerNormalization()(branch_lstm)

    branch_gru = layers.GRU(64, return_sequences=True,
                            kernel_regularizer=regularizers.l2(config['L2_REG']))(inputs)
    branch_gru = layers.LayerNormalization()(branch_gru)

    branch_cnn = layers.Conv1D(64, 5, padding='same', activation='relu',
                               kernel_regularizer=regularizers.l2(config['L2_REG']))(inputs)
    branch_cnn = layers.Conv1D(64, 3, padding='same', activation='relu',
                               kernel_regularizer=regularizers.l2(config['L2_REG']))(branch_cnn)
    branch_cnn = layers.LayerNormalization()(branch_cnn)

    fused = GatingLayer(num_branches=3)([branch_lstm, branch_gru, branch_cnn])
    fused = layers.Dropout(config['DROPOUT_RATE'])(fused)

    # BiLSTM layers for sequential modeling
    x = layers.Bidirectional(
        layers.LSTM(config['LSTM_UNITS'][0],
                    return_sequences=True,
                    kernel_regularizer=regularizers.l2(config['L2_REG'])),
        name='bilstm_1'
    )(fused)
    x = layers.LayerNormalization()(x)
    x = layers.Dropout(config['DROPOUT_RATE'])(x)

    x = layers.Bidirectional(
        layers.LSTM(config['LSTM_UNITS'][1],
                    return_sequences=True,
                    kernel_regularizer=regularizers.l2(config['L2_REG'])),
        name='bilstm_2'
    )(x)
    x = layers.LayerNormalization()(x)
    x = layers.Dropout(config['DROPOUT_RATE'])(x)

    # Attention layer
    context = AttentionLayer()(x)

    # Dense head
    x = layers.Dense(config['DENSE_UNITS'], activation='relu')(context)
    x = layers.Dropout(config['DROPOUT_RATE'])(x)

    outputs = layers.Dense(1, activation='linear', name='rul_output')(x)

    model = models.Model(inputs, outputs, name='Gated_Attention_BiLSTM')

    opt = optimizers.Adam(learning_rate=config['LEARNING_RATE'])
    model.compile(
        optimizer=opt,
        loss=tf.keras.losses.Huber(delta=1.0),
        metrics=['mae', 'mse']
    )
    return model


# ============================================================
# Train with Advanced Callbacks
# ============================================================

def train_model_with_cv(X_train, y_train, engine_ids, input_shape, config, n_splits=5):
    from sklearn.model_selection import GroupKFold

    gkf = GroupKFold(n_splits=n_splits)
    results, models_list = [], []

    for fold, (tr_idx, val_idx) in enumerate(gkf.split(X_train, y_train, engine_ids), 1):
        print(f"\n{'='*25} FOLD {fold}/{n_splits} {'='*25}")
        X_tr, X_val = X_train[tr_idx], X_train[val_idx]
        y_tr, y_val = y_train[tr_idx], y_train[val_idx]

        model = build_gated_attention_bilstm(input_shape, config)

        cb = [
            callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=10, min_lr=1e-6),
            callbacks.EarlyStopping(monitor='val_loss', patience=config['PATIENCE'],
                                    restore_best_weights=True),
            callbacks.ModelCheckpoint(f"best_fold_{fold}.h5", save_best_only=True)
        ]

        history = model.fit(
            X_tr, y_tr,
            validation_data=(X_val, y_val),
            epochs=config['EPOCHS'],
            batch_size=config['BATCH_SIZE'],
            verbose=1,
            callbacks=cb
        )

        val_loss, val_mae, val_mse = model.evaluate(X_val, y_val, verbose=0)
        val_rmse = np.sqrt(val_mse)

        y_pred = model.predict(X_val, verbose=0).flatten()
        val_r2 = r2_score(y_val, y_pred)

        results.append({'fold': fold, 'mae': val_mae, 'rmse': val_rmse, 'r2': val_r2})
        models_list.append(model)

        print(f"Fold {fold} Results -> MAE: {val_mae:.4f}, RMSE: {val_rmse:.4f}, R²: {val_r2:.4f}")

    print("\n=== Cross-Validation Summary ===")
    avg_mae = np.mean([r['mae'] for r in results])
    avg_rmse = np.mean([r['rmse'] for r in results])
    avg_r2 = np.mean([r['r2'] for r in results])
    print(f"MAE: {avg_mae:.4f}, RMSE: {avg_rmse:.4f}, R²: {avg_r2:.4f}")

    best_model_idx = np.argmax([r['r2'] for r in results])
    print(f"\nBest Fold: {best_model_idx + 1}")
    return models_list[best_model_idx], results


# ============================================================
# Execute Training
# ============================================================

input_shape = (X_train.shape[1], X_train.shape[2])
best_model, cv_results = train_model_with_cv(X_train, y_train, train_engine_ids, input_shape, CONFIG, CONFIG['N_SPLITS'])

# ============================================================
# Evaluate on Test Set
# ============================================================

y_test_pred_all = best_model.predict(X_test, verbose=0).flatten()
y_test_pred_all = np.clip(y_test_pred_all, 0, None)

# Take last window per engine
unique_engines = sorted(set(test_engine_ids))
y_true, y_pred = [], []
for eng_id in unique_engines:
    mask = test_engine_ids == eng_id
    y_pred.append(y_test_pred_all[mask][-1])
    y_true.append(df_test_RUL.iloc[int(eng_id) - 1]['RUL'])

y_true, y_pred = np.array(y_true), np.array(y_pred)
test_mae = mean_absolute_error(y_true, y_pred)
test_rmse = np.sqrt(mean_squared_error(y_true, y_pred))
test_r2 = r2_score(y_true, y_pred)

print(f"\n✅ Optimized Test Results:")
print(f"  MAE:  {test_mae:.4f}")
print(f"  RMSE: {test_rmse:.4f}")
print(f"  R²:   {test_r2:.4f}")

if test_r2 >= 0.85:
    print("\n🏆 EXCELLENT PERFORMANCE ACHIEVED!")

Optimized Configuration:
  WINDOW_SIZE: 40
  STRIDE: 2
  LSTM_UNITS: [128, 64]
  DENSE_UNITS: 80
  DROPOUT_RATE: 0.3
  L2_REG: 0.001
  BATCH_SIZE: 32
  EPOCHS: 200
  LEARNING_RATE: 0.0005
  PATIENCE: 35
  N_SPLITS: 5
Training sequences: (25826, 40, 24)
Test sequences: (15929, 40, 24)

========================= FOLD 1/5 =========================
Epoch 1/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 50.8152 - mae: 50.4979 - mse: 3877.2234

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

646/646 ━━━━━━━━━━━━━━━━━━━━ 37s 36ms/step - loss: 50.7904 - mae: 50.4732 - mse: 3874.3933 - val_loss: 17.4876 - val_mae: 17.3010 - val_mse: 531.1335 - learning_rate: 5.0000e-04
Epoch 2/200
645/646 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 20.3304 - mae: 20.1569 - mse: 722.7783

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

646/646 ━━━━━━━━━━━━━━━━━━━━ 21s 32ms/step - loss: 20.3298 - mae: 20.1564 - mse: 722.7396 - val_loss: 16.2561 - val_mae: 16.1149 - val_mse: 480.7980 - learning_rate: 5.0000e-04
Epoch 3/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 19.3134 - mae: 19.1802 - mse: 661.5758

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

646/646 ━━━━━━━━━━━━━━━━━━━━ 43s 34ms/step - loss: 19.3130 - mae: 19.1798 - mse: 661.5458 - val_loss: 15.8711 - val_mae: 15.7690 - val_mse: 435.7366 - learning_rate: 5.0000e-04
Epoch 4/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 21s 32ms/step - loss: 18.0746 - mae: 17.9787 - mse: 581.7769 - val_loss: 16.1993 - val_mae: 16.1287 - val_mse: 471.3832 - learning_rate: 5.0000e-04
Epoch 5/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 24s 37ms/step - loss: 17.2386 - mae: 17.1717 - mse: 536.9205 - val_loss: 16.2754 - val_mae: 16.2262 - val_mse: 464.8203 - learning_rate: 5.0000e-04
Epoch 6/200
645/646 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 16.3903 - mae: 16.3419 - mse: 491.1798

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

646/646 ━━━━━━━━━━━━━━━━━━━━ 39s 34ms/step - loss: 16.3898 - mae: 16.3414 - mse: 491.1417 - val_loss: 14.3320 - val_mae: 14.2978 - val_mse: 365.0586 - learning_rate: 5.0000e-04
Epoch 7/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 20s 31ms/step - loss: 15.8148 - mae: 15.7810 - mse: 457.8661 - val_loss: 14.8094 - val_mae: 14.7845 - val_mse: 421.8791 - learning_rate: 5.0000e-04
Epoch 8/200
645/646 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 15.5456 - mae: 15.5170 - mse: 442.4420

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - loss: 15.5450 - mae: 15.5164 - mse: 442.4065 - val_loss: 13.7467 - val_mae: 13.7245 - val_mse: 356.6982 - learning_rate: 5.0000e-04
Epoch 9/200
645/646 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 14.8208 - mae: 14.7942 - mse: 406.1537

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

646/646 ━━━━━━━━━━━━━━━━━━━━ 21s 32ms/step - loss: 14.8211 - mae: 14.7945 - mse: 406.1677 - val_loss: 13.4682 - val_mae: 13.4455 - val_mse: 356.0831 - learning_rate: 5.0000e-04
Epoch 10/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 21s 33ms/step - loss: 14.5520 - mae: 14.5241 - mse: 389.1342 - val_loss: 14.0147 - val_mae: 13.9890 - val_mse: 389.1988 - learning_rate: 5.0000e-04
Epoch 11/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 21s 32ms/step - loss: 13.9986 - mae: 13.9681 - mse: 359.7132 - val_loss: 15.2269 - val_mae: 15.1958 - val_mse: 431.4678 - learning_rate: 5.0000e-04
Epoch 12/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 21s 33ms/step - loss: 13.5590 - mae: 13.5217 - mse: 339.2905 - val_loss: 15.7848 - val_mae: 15.7468 - val_mse: 450.1996 - learning_rate: 5.0000e-04
Epoch 13/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 21s 33ms/step - loss: 13.2509 - mae: 13.2054 - mse: 322.2380 - val_loss: 15.3101 - val_mae: 15.2637 - val_mse: 451.2315 - learning_rate: 5.0000e-04
Epoch 14/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 42s 34ms/step - loss: 12.7964 - mae: 12.7423 - mse: 301.2932 - val_loss: 15.1439 - val_mae: 15.0888 - val_mse: 431.5673 - learning_rate: 5.0000e-04
Epoch 15/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 21s 33ms/step - loss: 12.3121 - mae: 12.2490 - mse: 282.7234 - val_loss: 14.3631 - val_mae: 14.3021 - val_mse: 405.8054 - learning_rate: 5.0000e-04
Epoch 16/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - loss: 12.1401 - mae: 12.0701 - mse: 271.2634 - val_loss: 16.2942 - val_mae: 16.2255 - val_mse: 521.3166 - learning_rate: 5.0000e-04
Epoch 17/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 21s 33ms/step - loss: 11.7123 - mae: 11.6366 - mse: 252.7663 - val_loss: 14.8069 - val_mae: 14.7342 - val_mse: 432.5430 - learning_rate: 5.0000e-04
Epoch 18/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - loss: 11.5240 - mae: 11.4427 - mse: 245.5629 - val_loss: 14.6729 - val_mae: 14.5943 - val_mse: 459.5248 - learning_rate: 5.0000e-04
Epoch 19/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - loss: 11.4972 - mae: 11.4112 - mse: 242.1095 - val_loss: 14.6269 - val_mae: 14.5447 - val_mse: 444.8801 - learning_rate: 5.0000e-04
Epoch 20/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 21s 33ms/step - loss: 10.7358 - mae: 10.6484 - mse: 212.0529 - val_loss: 14.7364 - val_mae: 14.6614 - val_mse: 462.7405 - learning_rate: 2.5000e-04
Epoch 21/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 23s 35ms/step - loss: 10.3394 - mae: 10.2574 - mse: 199.6083 - val_loss: 14.8644 - val_mae: 14.7969 - val_mse: 463.4775 - learning_rate: 2.5000e-04
Epoch 22/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 21s 32ms/step - loss: 10.5355 - mae: 10.4614 - mse: 209.9429 - val_loss: 15.1431 - val_mae: 15.0813 - val_mse: 472.3425 - learning_rate: 2.5000e-04
Epoch 23/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - loss: 10.3684 - mae: 10.2991 - mse: 201.2400 - val_loss: 15.2181 - val_mae: 15.1558 - val_mse: 509.5255 - learning_rate: 2.5000e-04
Epoch 24/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - loss: 10.3211 - mae: 10.2549 - mse: 198.5070 - val_loss: 14.8367 - val_mae: 14.7829 - val_mse: 439.5874 - learning_rate: 2.5000e-04
Epoch 25/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 21s 33ms/step - loss: 10.0840 - mae: 10.0219 - mse: 189.2008 - val_loss: 15.4005 - val_mae: 15.3525 - val_mse: 473.4876 - learning_rate: 2.5000e-04
Epoch 26/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - loss: 9.8786 - mae: 9.8212 - mse: 182.3113 - val_loss: 14.4715 - val_mae: 14.4272 - val_mse: 439.5172 - learning_rate: 2.5000e-04
Epoch 27/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 21s 32ms/step - loss: 10.0587 - mae: 10.0045 - mse: 189.5789 - val_loss: 15.0306 - val_mae: 14.9900 - val_mse: 465.2381 - learning_rate: 2.5000e-04
Epoch 28/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - loss: 9.9987 - mae: 9.9482 - mse: 186.6266 - val_loss: 14.6761 - val_mae: 14.6362 - val_mse: 463.0749 - learning_rate: 2.5000e-04
Epoch 29/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 20s 32ms/step - loss: 9.9152 - mae: 9.8683 - mse: 183.2408 - val_loss: 15.7167 - val_mae: 15.6817 - val_mse: 497.9868 - learning_rate: 2.5000e-04
Epoch 30/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - loss: 9.7470 - mae: 9.7019 - mse: 176.4366 - val_loss: 14.8320 - val_mae: 14.8010 - val_mse: 445.1966 - learning_rate: 1.2500e-04
Epoch 31/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 21s 32ms/step - loss: 9.5640 - mae: 9.5233 - mse: 171.8836 - val_loss: 13.9397 - val_mae: 13.9117 - val_mse: 419.0522 - learning_rate: 1.2500e-04
Epoch 32/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - loss: 9.4961 - mae: 9.4588 - mse: 168.7809 - val_loss: 14.2477 - val_mae: 14.2246 - val_mse: 435.4025 - learning_rate: 1.2500e-04
Epoch 33/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 21s 33ms/step - loss: 9.4573 - mae: 9.4251 - mse: 168.5344 - val_loss: 14.7573 - val_mae: 14.7395 - val_mse: 456.3089 - learning_rate: 1.2500e-04
Epoch 34/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 21s 33ms/step - loss: 9.2584 - mae: 9.2301 - mse: 159.5771 - val_loss: 14.9219 - val_mae: 14.9077 - val_mse: 453.3125 - learning_rate: 1.2500e-04
Epoch 35/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 35ms/step - loss: 9.3560 - mae: 9.3300 - mse: 163.1470 - val_loss: 15.4376 - val_mae: 15.4257 - val_mse: 473.4482 - learning_rate: 1.2500e-04
Epoch 36/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 21s 32ms/step - loss: 9.2996 - mae: 9.2780 - mse: 159.7429 - val_loss: 14.5280 - val_mae: 14.5201 - val_mse: 438.3884 - learning_rate: 1.2500e-04
Epoch 37/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - loss: 9.4276 - mae: 9.4099 - mse: 163.8418 - val_loss: 15.4533 - val_mae: 15.4484 - val_mse: 489.3521 - learning_rate: 1.2500e-04
Epoch 38/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 21s 32ms/step - loss: 9.1652 - mae: 9.1488 - mse: 159.5903 - val_loss: 15.3224 - val_mae: 15.3219 - val_mse: 463.3211 - learning_rate: 1.2500e-04
Epoch 39/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - loss: 9.1521 - mae: 9.1395 - mse: 157.9561 - val_loss: 14.2369 - val_mae: 14.2386 - val_mse: 440.9742 - learning_rate: 1.2500e-04
Epoch 40/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 21s 33ms/step - loss: 9.1286 - mae: 9.1185 - mse: 155.2259 - val_loss: 15.3291 - val_mae: 15.3340 - val_mse: 475.8625 - learning_rate: 6.2500e-05
Epoch 41/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 23s 35ms/step - loss: 9.1016 - mae: 9.0940 - mse: 155.0068 - val_loss: 15.1463 - val_mae: 15.1523 - val_mse: 469.7975 - learning_rate: 6.2500e-05
Epoch 42/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - loss: 9.0818 - mae: 9.0756 - mse: 155.4708 - val_loss: 15.3651 - val_mae: 15.3738 - val_mse: 486.5240 - learning_rate: 6.2500e-05
Epoch 43/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 21s 32ms/step - loss: 9.0398 - mae: 9.0356 - mse: 155.1091 - val_loss: 14.7449 - val_mae: 14.7551 - val_mse: 451.2444 - learning_rate: 6.2500e-05
Epoch 44/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - loss: 9.0305 - mae: 9.0285 - mse: 153.5350 - val_loss: 14.6673 - val_mae: 14.6793 - val_mse: 458.4362 - learning_rate: 6.2500e-05
Fold 1 Results -> MAE: 13.4455, RMSE: 18.8702, R²: 0.7954

========================= FOLD 2/5 =========================
Epoch 1/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 44.8469 - mae: 44.5105 - mse: 3207.0317

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

646/646 ━━━━━━━━━━━━━━━━━━━━ 32s 36ms/step - loss: 44.8233 - mae: 44.4870 - mse: 3204.5283 - val_loss: 18.3724 - val_mae: 18.1357 - val_mse: 560.3383 - learning_rate: 5.0000e-04
Epoch 2/200
645/646 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 18.6133 - mae: 18.3874 - mse: 635.8629

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 33ms/step - loss: 18.6118 - mae: 18.3860 - mse: 635.7626 - val_loss: 16.7212 - val_mae: 16.5422 - val_mse: 514.5512 - learning_rate: 5.0000e-04
Epoch 3/200
645/646 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 17.2206 - mae: 17.0504 - mse: 550.5004

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

646/646 ━━━━━━━━━━━━━━━━━━━━ 41s 34ms/step - loss: 17.2197 - mae: 17.0494 - mse: 550.4478 - val_loss: 16.1646 - val_mae: 16.0319 - val_mse: 480.4309 - learning_rate: 5.0000e-04
Epoch 4/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 16.6001 - mae: 16.4717 - mse: 513.4243

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

646/646 ━━━━━━━━━━━━━━━━━━━━ 21s 32ms/step - loss: 16.5997 - mae: 16.4713 - mse: 513.3990 - val_loss: 14.1189 - val_mae: 14.0163 - val_mse: 426.1070 - learning_rate: 5.0000e-04
Epoch 5/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 33ms/step - loss: 15.7962 - mae: 15.6969 - mse: 470.3832 - val_loss: 14.9215 - val_mae: 14.8434 - val_mse: 442.0965 - learning_rate: 5.0000e-04
Epoch 6/200
645/646 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 15.3130 - mae: 15.2336 - mse: 444.7102

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

646/646 ━━━━━━━━━━━━━━━━━━━━ 20s 32ms/step - loss: 15.3119 - mae: 15.2325 - mse: 444.6403 - val_loss: 13.3979 - val_mae: 13.3316 - val_mse: 391.8013 - learning_rate: 5.0000e-04
Epoch 7/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 14.7800 - mae: 14.7137 - mse: 417.5825

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - loss: 14.7796 - mae: 14.7133 - mse: 417.5529 - val_loss: 13.3645 - val_mae: 13.3096 - val_mse: 422.8469 - learning_rate: 5.0000e-04
Epoch 8/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 40s 33ms/step - loss: 14.4807 - mae: 14.4253 - mse: 404.0944 - val_loss: 13.4152 - val_mae: 13.3683 - val_mse: 397.6692 - learning_rate: 5.0000e-04
Epoch 9/200
645/646 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 13.9548 - mae: 13.9038 - mse: 374.7551

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - loss: 13.9539 - mae: 13.9029 - mse: 374.7020 - val_loss: 12.6601 - val_mae: 12.6111 - val_mse: 355.0085 - learning_rate: 5.0000e-04
Epoch 10/200
645/646 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 13.3428 - mae: 13.2893 - mse: 343.3435

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

646/646 ━━━━━━━━━━━━━━━━━━━━ 21s 32ms/step - loss: 13.3421 - mae: 13.2887 - mse: 343.3042 - val_loss: 12.5136 - val_mae: 12.4621 - val_mse: 368.3514 - learning_rate: 5.0000e-04
Epoch 11/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 33ms/step - loss: 13.0811 - mae: 13.0234 - mse: 326.1682 - val_loss: 13.4194 - val_mae: 13.3627 - val_mse: 378.5752 - learning_rate: 5.0000e-04
Epoch 12/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 21s 32ms/step - loss: 12.3832 - mae: 12.3211 - mse: 291.6566 - val_loss: 12.9671 - val_mae: 12.9055 - val_mse: 361.8841 - learning_rate: 5.0000e-04
Epoch 13/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 41s 32ms/step - loss: 12.0465 - mae: 11.9784 - mse: 271.9960 - val_loss: 13.6136 - val_mae: 13.5418 - val_mse: 381.5606 - learning_rate: 5.0000e-04
Epoch 14/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 33ms/step - loss: 11.4090 - mae: 11.3307 - mse: 244.6163 - val_loss: 12.7573 - val_mae: 12.6769 - val_mse: 348.9638 - learning_rate: 5.0000e-04
Epoch 15/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 33ms/step - loss: 11.0827 - mae: 10.9938 - mse: 228.7304 - val_loss: 13.5705 - val_mae: 13.4809 - val_mse: 366.8376 - learning_rate: 5.0000e-04
Epoch 16/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 41s 34ms/step - loss: 10.8117 - mae: 10.7131 - mse: 218.3718 - val_loss: 14.0496 - val_mae: 13.9534 - val_mse: 419.1460 - learning_rate: 5.0000e-04
Epoch 17/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 41s 34ms/step - loss: 10.2827 - mae: 10.1798 - mse: 190.7137 - val_loss: 15.4229 - val_mae: 15.3208 - val_mse: 449.6318 - learning_rate: 5.0000e-04
Epoch 18/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 20s 31ms/step - loss: 10.0653 - mae: 9.9533 - mse: 181.5885 - val_loss: 13.7442 - val_mae: 13.6329 - val_mse: 402.3215 - learning_rate: 5.0000e-04
Epoch 19/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - loss: 10.0606 - mae: 9.9410 - mse: 182.8312 - val_loss: 13.4700 - val_mae: 13.3516 - val_mse: 395.1570 - learning_rate: 5.0000e-04
Epoch 20/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 21s 32ms/step - loss: 9.5549 - mae: 9.4283 - mse: 163.6603 - val_loss: 13.2695 - val_mae: 13.1477 - val_mse: 388.1357 - learning_rate: 5.0000e-04
Epoch 21/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - loss: 8.9411 - mae: 8.8119 - mse: 141.1124 - val_loss: 13.4031 - val_mae: 13.2893 - val_mse: 400.6954 - learning_rate: 2.5000e-04
Epoch 22/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 21s 33ms/step - loss: 8.5965 - mae: 8.4747 - mse: 131.9944 - val_loss: 13.8247 - val_mae: 13.7188 - val_mse: 399.2014 - learning_rate: 2.5000e-04
Epoch 23/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 21s 33ms/step - loss: 8.5896 - mae: 8.4745 - mse: 131.7123 - val_loss: 13.6330 - val_mae: 13.5322 - val_mse: 397.6758 - learning_rate: 2.5000e-04
Epoch 24/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 33ms/step - loss: 8.4274 - mae: 8.3201 - mse: 126.9972 - val_loss: 13.9048 - val_mae: 13.8101 - val_mse: 421.4626 - learning_rate: 2.5000e-04
Epoch 25/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 41s 34ms/step - loss: 8.3907 - mae: 8.2883 - mse: 124.8913 - val_loss: 13.8101 - val_mae: 13.7203 - val_mse: 400.3528 - learning_rate: 2.5000e-04
Epoch 26/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 21s 32ms/step - loss: 8.1324 - mae: 8.0348 - mse: 116.5888 - val_loss: 14.1050 - val_mae: 14.0215 - val_mse: 409.1178 - learning_rate: 2.5000e-04
Epoch 27/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - loss: 8.1274 - mae: 8.0359 - mse: 117.3527 - val_loss: 14.4016 - val_mae: 14.3230 - val_mse: 441.4651 - learning_rate: 2.5000e-04
Epoch 28/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 21s 32ms/step - loss: 8.0159 - mae: 7.9281 - mse: 114.0319 - val_loss: 13.8149 - val_mae: 13.7418 - val_mse: 425.2972 - learning_rate: 2.5000e-04
Epoch 29/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - loss: 8.1759 - mae: 8.0939 - mse: 119.3248 - val_loss: 14.1250 - val_mae: 14.0576 - val_mse: 405.5968 - learning_rate: 2.5000e-04
Epoch 30/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 24s 37ms/step - loss: 7.9950 - mae: 7.9165 - mse: 112.9925 - val_loss: 13.1693 - val_mae: 13.0675 - val_mse: 413.2188 - learning_rate: 2.5000e-04
Epoch 31/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - loss: 7.8589 - mae: 7.7851 - mse: 108.9939 - val_loss: 13.8865 - val_mae: 13.8282 - val_mse: 405.9550 - learning_rate: 1.2500e-04
Epoch 32/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - loss: 7.7173 - mae: 7.6471 - mse: 107.2645 - val_loss: 13.9757 - val_mae: 13.9214 - val_mse: 413.9477 - learning_rate: 1.2500e-04
Epoch 33/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - loss: 7.6408 - mae: 7.5750 - mse: 104.9629 - val_loss: 14.2608 - val_mae: 14.2109 - val_mse: 425.9235 - learning_rate: 1.2500e-04
Epoch 34/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 33ms/step - loss: 7.5912 - mae: 7.5313 - mse: 103.2703 - val_loss: 14.0977 - val_mae: 14.0509 - val_mse: 431.0662 - learning_rate: 1.2500e-04
Epoch 35/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 35ms/step - loss: 7.5390 - mae: 7.4813 - mse: 102.6112 - val_loss: 14.4324 - val_mae: 14.3914 - val_mse: 433.1458 - learning_rate: 1.2500e-04
Epoch 36/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 41s 34ms/step - loss: 7.4093 - mae: 7.3574 - mse: 99.1179 - val_loss: 13.7827 - val_mae: 13.7413 - val_mse: 412.8527 - learning_rate: 1.2500e-04
Epoch 37/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 21s 32ms/step - loss: 7.6733 - mae: 7.6246 - mse: 106.4902 - val_loss: 13.9097 - val_mae: 13.8703 - val_mse: 432.9004 - learning_rate: 1.2500e-04
Epoch 38/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 35ms/step - loss: 7.5092 - mae: 7.4657 - mse: 100.7886 - val_loss: 13.8922 - val_mae: 13.8644 - val_mse: 405.1818 - learning_rate: 1.2500e-04
Epoch 39/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - loss: 7.4609 - mae: 7.4207 - mse: 100.1754 - val_loss: 13.9245 - val_mae: 13.9002 - val_mse: 409.9999 - learning_rate: 1.2500e-04
Epoch 40/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 33ms/step - loss: 7.5176 - mae: 7.4823 - mse: 101.9150 - val_loss: 13.7649 - val_mae: 13.7412 - val_mse: 424.4857 - learning_rate: 1.2500e-04
Epoch 41/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 23s 35ms/step - loss: 7.2581 - mae: 7.2258 - mse: 96.2231 - val_loss: 13.9198 - val_mae: 13.9000 - val_mse: 428.8202 - learning_rate: 6.2500e-05
Epoch 42/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 41s 36ms/step - loss: 7.2357 - mae: 7.2047 - mse: 95.6983 - val_loss: 13.8549 - val_mae: 13.8380 - val_mse: 422.0235 - learning_rate: 6.2500e-05
Epoch 43/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 33ms/step - loss: 7.2563 - mae: 7.2273 - mse: 97.3913 - val_loss: 13.9544 - val_mae: 13.9406 - val_mse: 419.6062 - learning_rate: 6.2500e-05
Epoch 44/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 23s 35ms/step - loss: 7.2175 - mae: 7.1919 - mse: 93.5634 - val_loss: 13.5997 - val_mae: 13.5855 - val_mse: 413.6107 - learning_rate: 6.2500e-05
Epoch 45/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 23s 36ms/step - loss: 7.1830 - mae: 7.1607 - mse: 94.1260 - val_loss: 13.8321 - val_mae: 13.8099 - val_mse: 430.7012 - learning_rate: 6.2500e-05
Fold 2 Results -> MAE: 12.4621, RMSE: 19.1925, R²: 0.7878

========================= FOLD 3/5 =========================
Epoch 1/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 49.1306 - mae: 48.8161 - mse: 3587.1123

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

646/646 ━━━━━━━━━━━━━━━━━━━━ 33s 36ms/step - loss: 49.1088 - mae: 48.7944 - mse: 3584.6868 - val_loss: 17.3935 - val_mae: 17.2417 - val_mse: 509.7935 - learning_rate: 5.0000e-04
Epoch 2/200
645/646 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 20.2875 - mae: 20.1462 - mse: 719.7460

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 33ms/step - loss: 20.2858 - mae: 20.1446 - mse: 719.6503 - val_loss: 14.1712 - val_mae: 14.0690 - val_mse: 390.8122 - learning_rate: 5.0000e-04
Epoch 3/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 21s 33ms/step - loss: 18.4035 - mae: 18.3114 - mse: 617.1940 - val_loss: 14.8753 - val_mae: 14.8181 - val_mse: 476.7603 - learning_rate: 5.0000e-04
Epoch 4/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 19.4824 - mae: 19.4270 - mse: 700.3588

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

646/646 ━━━━━━━━━━━━━━━━━━━━ 42s 34ms/step - loss: 19.4816 - mae: 19.4262 - mse: 700.2950 - val_loss: 14.0899 - val_mae: 14.0476 - val_mse: 399.6658 - learning_rate: 5.0000e-04
Epoch 5/200
645/646 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 17.5395 - mae: 17.5016 - mse: 567.1152

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

646/646 ━━━━━━━━━━━━━━━━━━━━ 20s 32ms/step - loss: 17.5389 - mae: 17.5010 - mse: 567.0671 - val_loss: 13.6758 - val_mae: 13.6589 - val_mse: 342.1850 - learning_rate: 5.0000e-04
Epoch 6/200
645/646 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 17.3212 - mae: 17.3047 - mse: 564.6406

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - loss: 17.3195 - mae: 17.3030 - mse: 564.5313 - val_loss: 12.3361 - val_mae: 12.3330 - val_mse: 317.0100 - learning_rate: 5.0000e-04
Epoch 7/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 16.0814 - mae: 16.0808 - mse: 488.5667

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - loss: 16.0812 - mae: 16.0806 - mse: 488.5483 - val_loss: 11.2996 - val_mae: 11.3119 - val_mse: 287.9047 - learning_rate: 5.0000e-04
Epoch 8/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 21s 33ms/step - loss: 15.9141 - mae: 15.9281 - mse: 482.8931 - val_loss: 12.7703 - val_mae: 12.7869 - val_mse: 351.2188 - learning_rate: 5.0000e-04
Epoch 9/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 21s 33ms/step - loss: 15.2233 - mae: 15.2416 - mse: 442.2921 - val_loss: 11.5086 - val_mae: 11.5425 - val_mse: 295.4460 - learning_rate: 5.0000e-04
Epoch 10/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 21s 32ms/step - loss: 14.6358 - mae: 14.6708 - mse: 410.4857 - val_loss: 11.4959 - val_mae: 11.5425 - val_mse: 300.8183 - learning_rate: 5.0000e-04
Epoch 11/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - loss: 14.2005 - mae: 14.2495 - mse: 389.9729 - val_loss: 11.8481 - val_mae: 11.9109 - val_mse: 315.0465 - learning_rate: 5.0000e-04
Epoch 12/200
645/646 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 13.9127 - mae: 13.9757 - mse: 372.4894

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

646/646 ━━━━━━━━━━━━━━━━━━━━ 41s 34ms/step - loss: 13.9127 - mae: 13.9756 - mse: 372.4908 - val_loss: 11.2391 - val_mae: 11.3122 - val_mse: 288.7245 - learning_rate: 5.0000e-04
Epoch 13/200
645/646 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 13.8026 - mae: 13.8763 - mse: 366.8363

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

646/646 ━━━━━━━━━━━━━━━━━━━━ 21s 32ms/step - loss: 13.8026 - mae: 13.8763 - mse: 366.8357 - val_loss: 10.1180 - val_mae: 10.1978 - val_mse: 244.2564 - learning_rate: 5.0000e-04
Epoch 14/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - loss: 13.6963 - mae: 13.7757 - mse: 365.3607 - val_loss: 11.3210 - val_mae: 11.4097 - val_mse: 283.3303 - learning_rate: 5.0000e-04
Epoch 15/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 20s 32ms/step - loss: 13.4751 - mae: 13.5593 - mse: 351.9623 - val_loss: 10.9713 - val_mae: 11.0587 - val_mse: 301.4951 - learning_rate: 5.0000e-04
Epoch 16/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 33ms/step - loss: 13.1867 - mae: 13.2703 - mse: 340.1775 - val_loss: 10.7978 - val_mae: 10.8805 - val_mse: 264.0594 - learning_rate: 5.0000e-04
Epoch 17/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 21s 32ms/step - loss: 13.0706 - mae: 13.1498 - mse: 335.7064 - val_loss: 12.8939 - val_mae: 12.9765 - val_mse: 327.9698 - learning_rate: 5.0000e-04
Epoch 18/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 43s 34ms/step - loss: 12.8153 - mae: 12.8945 - mse: 318.9538 - val_loss: 10.9006 - val_mae: 10.9799 - val_mse: 303.0311 - learning_rate: 5.0000e-04
Epoch 19/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 42s 35ms/step - loss: 12.7421 - mae: 12.8206 - mse: 316.5526 - val_loss: 12.0345 - val_mae: 12.1167 - val_mse: 320.9700 - learning_rate: 5.0000e-04
Epoch 20/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 21s 32ms/step - loss: 12.3317 - mae: 12.4059 - mse: 298.6573 - val_loss: 11.1858 - val_mae: 11.2599 - val_mse: 307.8380 - learning_rate: 5.0000e-04
Epoch 21/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - loss: 12.2140 - mae: 12.2826 - mse: 298.0663 - val_loss: 12.3312 - val_mae: 12.3939 - val_mse: 349.7326 - learning_rate: 5.0000e-04
Epoch 22/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 33ms/step - loss: 11.8967 - mae: 11.9578 - mse: 278.4792 - val_loss: 12.1895 - val_mae: 12.2503 - val_mse: 294.2637 - learning_rate: 5.0000e-04
Epoch 23/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 21s 33ms/step - loss: 11.7396 - mae: 11.7958 - mse: 270.5502 - val_loss: 12.1620 - val_mae: 12.2165 - val_mse: 304.1868 - learning_rate: 5.0000e-04
Epoch 24/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - loss: 10.9466 - mae: 10.9956 - mse: 238.8768 - val_loss: 11.5358 - val_mae: 11.5947 - val_mse: 297.9030 - learning_rate: 2.5000e-04
Epoch 25/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 21s 32ms/step - loss: 10.4080 - mae: 10.4630 - mse: 215.7450 - val_loss: 11.2101 - val_mae: 11.2723 - val_mse: 287.0541 - learning_rate: 2.5000e-04
Epoch 26/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 41s 33ms/step - loss: 10.2979 - mae: 10.3539 - mse: 213.0129 - val_loss: 11.5777 - val_mae: 11.6417 - val_mse: 315.2010 - learning_rate: 2.5000e-04
Epoch 27/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - loss: 10.1936 - mae: 10.2505 - mse: 205.8777 - val_loss: 11.6900 - val_mae: 11.7544 - val_mse: 320.5411 - learning_rate: 2.5000e-04
Epoch 28/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - loss: 9.9999 - mae: 10.0566 - mse: 200.7381 - val_loss: 11.3927 - val_mae: 11.4559 - val_mse: 317.5862 - learning_rate: 2.5000e-04
Epoch 29/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 41s 34ms/step - loss: 9.8462 - mae: 9.9033 - mse: 192.3259 - val_loss: 11.5388 - val_mae: 11.6038 - val_mse: 327.7465 - learning_rate: 2.5000e-04
Epoch 30/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 41s 34ms/step - loss: 9.7193 - mae: 9.7765 - mse: 186.5661 - val_loss: 11.8238 - val_mae: 11.8879 - val_mse: 322.4417 - learning_rate: 2.5000e-04
Epoch 31/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 21s 32ms/step - loss: 9.4779 - mae: 9.5341 - mse: 176.7444 - val_loss: 12.6601 - val_mae: 12.7238 - val_mse: 342.9736 - learning_rate: 2.5000e-04
Epoch 32/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - loss: 9.5242 - mae: 9.5799 - mse: 178.6854 - val_loss: 12.5266 - val_mae: 12.5890 - val_mse: 342.2397 - learning_rate: 2.5000e-04
Epoch 33/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 21s 33ms/step - loss: 9.3973 - mae: 9.4514 - mse: 174.9222 - val_loss: 12.3472 - val_mae: 12.4086 - val_mse: 350.3590 - learning_rate: 2.5000e-04
Epoch 34/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 42s 35ms/step - loss: 9.0505 - mae: 9.1030 - mse: 161.1169 - val_loss: 12.0381 - val_mae: 12.1017 - val_mse: 344.9884 - learning_rate: 1.2500e-04
Epoch 35/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 21s 32ms/step - loss: 8.9157 - mae: 8.9698 - mse: 157.1413 - val_loss: 11.8995 - val_mae: 11.9561 - val_mse: 349.6649 - learning_rate: 1.2500e-04
Epoch 36/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 41s 32ms/step - loss: 8.9573 - mae: 9.0139 - mse: 159.5273 - val_loss: 12.5889 - val_mae: 12.6552 - val_mse: 368.5753 - learning_rate: 1.2500e-04
Epoch 37/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - loss: 8.6134 - mae: 8.6709 - mse: 148.6437 - val_loss: 11.5876 - val_mae: 11.6439 - val_mse: 349.7895 - learning_rate: 1.2500e-04
Epoch 38/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 21s 33ms/step - loss: 8.5742 - mae: 8.6330 - mse: 147.0900 - val_loss: 12.2210 - val_mae: 12.2919 - val_mse: 351.5616 - learning_rate: 1.2500e-04
Epoch 39/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 21s 33ms/step - loss: 8.5844 - mae: 8.6457 - mse: 146.8590 - val_loss: 12.2623 - val_mae: 12.3325 - val_mse: 350.3207 - learning_rate: 1.2500e-04
Epoch 40/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - loss: 8.5406 - mae: 8.6025 - mse: 144.1583 - val_loss: 11.5818 - val_mae: 11.6520 - val_mse: 331.3187 - learning_rate: 1.2500e-04
Epoch 41/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 21s 33ms/step - loss: 8.7015 - mae: 8.7633 - mse: 150.2819 - val_loss: 12.1943 - val_mae: 12.2669 - val_mse: 355.1587 - learning_rate: 1.2500e-04
Epoch 42/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - loss: 8.5043 - mae: 8.5681 - mse: 143.8210 - val_loss: 11.9661 - val_mae: 12.0408 - val_mse: 358.9708 - learning_rate: 1.2500e-04
Epoch 43/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 21s 32ms/step - loss: 8.4937 - mae: 8.5589 - mse: 143.8421 - val_loss: 11.8287 - val_mae: 11.9039 - val_mse: 337.9045 - learning_rate: 1.2500e-04
Epoch 44/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - loss: 8.3753 - mae: 8.4404 - mse: 139.8342 - val_loss: 12.1692 - val_mae: 12.2438 - val_mse: 363.3191 - learning_rate: 6.2500e-05
Epoch 45/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 33ms/step - loss: 8.1742 - mae: 8.2403 - mse: 133.9978 - val_loss: 12.2527 - val_mae: 12.3308 - val_mse: 354.6126 - learning_rate: 6.2500e-05
Epoch 46/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 42s 35ms/step - loss: 8.2303 - mae: 8.2982 - mse: 135.8311 - val_loss: 12.5747 - val_mae: 12.6542 - val_mse: 379.8710 - learning_rate: 6.2500e-05
Epoch 47/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 21s 33ms/step - loss: 8.2644 - mae: 8.3333 - mse: 138.0233 - val_loss: 11.8098 - val_mae: 11.8855 - val_mse: 350.4861 - learning_rate: 6.2500e-05
Epoch 48/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - loss: 8.2793 - mae: 8.3501 - mse: 135.5186 - val_loss: 12.1720 - val_mae: 12.2511 - val_mse: 358.9074 - learning_rate: 6.2500e-05
Fold 3 Results -> MAE: 10.1978, RMSE: 15.6287, R²: 0.8594

========================= FOLD 4/5 =========================
Epoch 1/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 47.2401 - mae: 46.9031 - mse: 3509.4602

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

646/646 ━━━━━━━━━━━━━━━━━━━━ 35s 39ms/step - loss: 47.2152 - mae: 46.8783 - mse: 3506.7288 - val_loss: 19.5420 - val_mae: 19.3146 - val_mse: 676.9639 - learning_rate: 5.0000e-04
Epoch 2/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 19.6071 - mae: 19.3990 - mse: 680.1630

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - loss: 19.6063 - mae: 19.3983 - mse: 680.1147 - val_loss: 18.3610 - val_mae: 18.2143 - val_mse: 660.3483 - learning_rate: 5.0000e-04
Epoch 3/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 17.8840 - mae: 17.7501 - mse: 582.1865

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 35ms/step - loss: 17.8835 - mae: 17.7496 - mse: 582.1500 - val_loss: 17.0417 - val_mae: 16.9504 - val_mse: 544.8117 - learning_rate: 5.0000e-04
Epoch 4/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 16.8931 - mae: 16.8084 - mse: 524.7755

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

646/646 ━━━━━━━━━━━━━━━━━━━━ 21s 32ms/step - loss: 16.8927 - mae: 16.8080 - mse: 524.7480 - val_loss: 16.4093 - val_mae: 16.3519 - val_mse: 555.7093 - learning_rate: 5.0000e-04
Epoch 5/200
645/646 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 15.9996 - mae: 15.9447 - mse: 471.8824

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 35ms/step - loss: 15.9987 - mae: 15.9437 - mse: 471.8410 - val_loss: 15.6032 - val_mae: 15.5602 - val_mse: 523.3120 - learning_rate: 5.0000e-04
Epoch 6/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - loss: 15.2766 - mae: 15.2337 - mse: 438.0811 - val_loss: 15.9537 - val_mae: 15.9215 - val_mse: 497.8023 - learning_rate: 5.0000e-04
Epoch 7/200
645/646 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 14.6037 - mae: 14.5702 - mse: 398.6251

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

646/646 ━━━━━━━━━━━━━━━━━━━━ 21s 33ms/step - loss: 14.6025 - mae: 14.5691 - mse: 398.5669 - val_loss: 15.2773 - val_mae: 15.2475 - val_mse: 478.1182 - learning_rate: 5.0000e-04
Epoch 8/200
645/646 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 13.9601 - mae: 13.9276 - mse: 367.6746

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - loss: 13.9599 - mae: 13.9274 - mse: 367.6609 - val_loss: 15.1494 - val_mae: 15.1194 - val_mse: 491.7546 - learning_rate: 5.0000e-04
Epoch 9/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - loss: 13.6404 - mae: 13.6061 - mse: 349.8825 - val_loss: 17.5544 - val_mae: 17.5227 - val_mse: 647.3914 - learning_rate: 5.0000e-04
Epoch 10/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 13.0530 - mae: 13.0147 - mse: 327.6707

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

646/646 ━━━━━━━━━━━━━━━━━━━━ 41s 34ms/step - loss: 13.0529 - mae: 13.0146 - mse: 327.6588 - val_loss: 15.0834 - val_mae: 15.0453 - val_mse: 475.6856 - learning_rate: 5.0000e-04
Epoch 11/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - loss: 12.6616 - mae: 12.6182 - mse: 303.5032 - val_loss: 15.9808 - val_mae: 15.9397 - val_mse: 555.6730 - learning_rate: 5.0000e-04
Epoch 12/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 24s 37ms/step - loss: 12.3303 - mae: 12.2835 - mse: 292.1370 - val_loss: 15.8130 - val_mae: 15.7652 - val_mse: 537.6764 - learning_rate: 5.0000e-04
Epoch 13/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 11.7107 - mae: 11.6556 - mse: 260.8721

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - loss: 11.7107 - mae: 11.6555 - mse: 260.8655 - val_loss: 14.9134 - val_mae: 14.8558 - val_mse: 492.7033 - learning_rate: 5.0000e-04
Epoch 14/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 11.4574 - mae: 11.3924 - mse: 251.5015

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

646/646 ━━━━━━━━━━━━━━━━━━━━ 23s 35ms/step - loss: 11.4572 - mae: 11.3921 - mse: 251.4905 - val_loss: 14.0483 - val_mae: 13.9682 - val_mse: 479.4714 - learning_rate: 5.0000e-04
Epoch 15/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 23s 35ms/step - loss: 10.9517 - mae: 10.8813 - mse: 230.1181 - val_loss: 15.1772 - val_mae: 15.1025 - val_mse: 540.1029 - learning_rate: 5.0000e-04
Epoch 16/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 21s 33ms/step - loss: 10.9441 - mae: 10.8675 - mse: 226.5200 - val_loss: 15.6148 - val_mae: 15.5326 - val_mse: 558.9014 - learning_rate: 5.0000e-04
Epoch 17/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 41s 33ms/step - loss: 10.5077 - mae: 10.4222 - mse: 209.6331 - val_loss: 15.7108 - val_mae: 15.6275 - val_mse: 527.3074 - learning_rate: 5.0000e-04
Epoch 18/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 41s 34ms/step - loss: 10.2423 - mae: 10.1520 - mse: 197.9543 - val_loss: 15.4224 - val_mae: 15.3320 - val_mse: 525.3092 - learning_rate: 5.0000e-04
Epoch 19/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 21s 33ms/step - loss: 10.1399 - mae: 10.0471 - mse: 194.7675 - val_loss: 16.3345 - val_mae: 16.2450 - val_mse: 539.3436 - learning_rate: 5.0000e-04
Epoch 20/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - loss: 9.9324 - mae: 9.8361 - mse: 185.3311 - val_loss: 16.3886 - val_mae: 16.2969 - val_mse: 565.2721 - learning_rate: 5.0000e-04
Epoch 21/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 21s 32ms/step - loss: 9.8789 - mae: 9.7785 - mse: 182.6527 - val_loss: 16.2803 - val_mae: 16.1835 - val_mse: 563.9530 - learning_rate: 5.0000e-04
Epoch 22/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - loss: 9.6383 - mae: 9.5339 - mse: 177.6324 - val_loss: 15.7110 - val_mae: 15.6107 - val_mse: 547.1379 - learning_rate: 5.0000e-04
Epoch 23/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 33ms/step - loss: 9.3144 - mae: 9.2070 - mse: 163.5723 - val_loss: 16.6402 - val_mae: 16.5418 - val_mse: 567.8666 - learning_rate: 5.0000e-04
Epoch 24/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - loss: 9.5866 - mae: 9.4807 - mse: 170.4128 - val_loss: 15.6018 - val_mae: 15.4809 - val_mse: 558.0036 - learning_rate: 5.0000e-04
Epoch 25/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - loss: 8.8670 - mae: 8.7608 - mse: 148.2087 - val_loss: 15.9413 - val_mae: 15.8430 - val_mse: 573.4407 - learning_rate: 2.5000e-04
Epoch 26/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 21s 32ms/step - loss: 8.6159 - mae: 8.5193 - mse: 141.3616 - val_loss: 16.5305 - val_mae: 16.4496 - val_mse: 560.4969 - learning_rate: 2.5000e-04
Epoch 27/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - loss: 8.5597 - mae: 8.4704 - mse: 140.7852 - val_loss: 16.7523 - val_mae: 16.6780 - val_mse: 599.8368 - learning_rate: 2.5000e-04
Epoch 28/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 41s 34ms/step - loss: 8.4355 - mae: 8.3526 - mse: 136.6823 - val_loss: 16.2778 - val_mae: 16.2113 - val_mse: 566.1564 - learning_rate: 2.5000e-04
Epoch 29/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 21s 32ms/step - loss: 8.3671 - mae: 8.2918 - mse: 131.9062 - val_loss: 16.0895 - val_mae: 16.0277 - val_mse: 572.7822 - learning_rate: 2.5000e-04
Epoch 30/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 35ms/step - loss: 8.4690 - mae: 8.3998 - mse: 136.3071 - val_loss: 15.7016 - val_mae: 15.6327 - val_mse: 572.8174 - learning_rate: 2.5000e-04
Epoch 31/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - loss: 8.2926 - mae: 8.2281 - mse: 132.9369 - val_loss: 16.7839 - val_mae: 16.7353 - val_mse: 576.0612 - learning_rate: 2.5000e-04
Epoch 32/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 41s 35ms/step - loss: 8.2455 - mae: 8.1875 - mse: 129.2516 - val_loss: 16.3943 - val_mae: 16.3516 - val_mse: 563.8470 - learning_rate: 2.5000e-04
Epoch 33/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 33ms/step - loss: 8.2370 - mae: 8.1835 - mse: 126.3300 - val_loss: 16.2866 - val_mae: 16.2491 - val_mse: 578.3269 - learning_rate: 2.5000e-04
Epoch 34/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 35ms/step - loss: 8.1877 - mae: 8.1390 - mse: 125.6849 - val_loss: 16.3418 - val_mae: 16.3083 - val_mse: 581.5535 - learning_rate: 2.5000e-04
Epoch 35/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 21s 33ms/step - loss: 8.0669 - mae: 8.0228 - mse: 121.6701 - val_loss: 15.8049 - val_mae: 15.7763 - val_mse: 553.4446 - learning_rate: 1.2500e-04
Epoch 36/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - loss: 7.9277 - mae: 7.8881 - mse: 116.8162 - val_loss: 16.1633 - val_mae: 16.1405 - val_mse: 566.9312 - learning_rate: 1.2500e-04
Epoch 37/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 40s 33ms/step - loss: 7.7243 - mae: 7.6892 - mse: 111.0823 - val_loss: 16.0014 - val_mae: 15.9826 - val_mse: 564.0112 - learning_rate: 1.2500e-04
Epoch 38/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 35ms/step - loss: 7.8683 - mae: 7.8378 - mse: 115.9596 - val_loss: 15.8291 - val_mae: 15.8136 - val_mse: 576.9515 - learning_rate: 1.2500e-04
Epoch 39/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 21s 33ms/step - loss: 7.7142 - mae: 7.6877 - mse: 111.5980 - val_loss: 15.8813 - val_mae: 15.8585 - val_mse: 593.5524 - learning_rate: 1.2500e-04
Epoch 40/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 23s 35ms/step - loss: 7.7715 - mae: 7.7506 - mse: 112.6569 - val_loss: 16.1396 - val_mae: 16.1297 - val_mse: 579.7462 - learning_rate: 1.2500e-04
Epoch 41/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - loss: 7.6876 - mae: 7.6688 - mse: 111.0351 - val_loss: 16.0941 - val_mae: 16.0801 - val_mse: 579.5848 - learning_rate: 1.2500e-04
Epoch 42/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 42s 35ms/step - loss: 7.6749 - mae: 7.6623 - mse: 111.1731 - val_loss: 16.0605 - val_mae: 16.0639 - val_mse: 565.6598 - learning_rate: 1.2500e-04
Epoch 43/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 21s 33ms/step - loss: 7.4902 - mae: 7.4812 - mse: 104.6816 - val_loss: 16.3008 - val_mae: 16.3092 - val_mse: 582.6881 - learning_rate: 1.2500e-04
Epoch 44/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 23s 35ms/step - loss: 7.6118 - mae: 7.6068 - mse: 106.6789 - val_loss: 16.3155 - val_mae: 16.3099 - val_mse: 603.5050 - learning_rate: 1.2500e-04
Epoch 45/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 41s 35ms/step - loss: 7.4958 - mae: 7.4935 - mse: 104.5787 - val_loss: 16.3708 - val_mae: 16.3839 - val_mse: 577.4414 - learning_rate: 6.2500e-05
Epoch 46/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 21s 33ms/step - loss: 7.4171 - mae: 7.4168 - mse: 103.9008 - val_loss: 16.3061 - val_mae: 16.3215 - val_mse: 574.6044 - learning_rate: 6.2500e-05
Epoch 47/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 22s 35ms/step - loss: 7.4763 - mae: 7.4788 - mse: 104.6046 - val_loss: 16.4524 - val_mae: 16.4719 - val_mse: 578.3599 - learning_rate: 6.2500e-05
Epoch 48/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 23s 35ms/step - loss: 7.5017 - mae: 7.5070 - mse: 104.5356 - val_loss: 16.2467 - val_mae: 16.2671 - val_mse: 586.6497 - learning_rate: 6.2500e-05
Epoch 49/200
646/646 ━━━━━━━━━━━━━━━━━━━━ 41s 35ms/step - loss: 7.3768 - mae: 7.3855 - mse: 101.3644 - val_loss: 16.0245 - val_mae: 16.0480 - val_mse: 572.7324 - learning_rate: 6.2500e-05
Fold 4 Results -> MAE: 13.9682, RMSE: 21.8968, R²: 0.7241

========================= FOLD 5/5 =========================
Epoch 1/200
647/647 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 47.3350 - mae: 47.0097 - mse: 3417.8572

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

647/647 ━━━━━━━━━━━━━━━━━━━━ 33s 36ms/step - loss: 47.3123 - mae: 46.9871 - mse: 3415.4094 - val_loss: 17.9702 - val_mae: 17.7765 - val_mse: 581.1530 - learning_rate: 5.0000e-04
Epoch 2/200
647/647 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 18.8758 - mae: 18.6987 - mse: 637.8372

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

647/647 ━━━━━━━━━━━━━━━━━━━━ 22s 33ms/step - loss: 18.8756 - mae: 18.6985 - mse: 637.8194 - val_loss: 17.7783 - val_mae: 17.6537 - val_mse: 565.8199 - learning_rate: 5.0000e-04
Epoch 3/200
646/647 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 17.8587 - mae: 17.7456 - mse: 576.4385

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

647/647 ━━━━━━━━━━━━━━━━━━━━ 22s 35ms/step - loss: 17.8583 - mae: 17.7452 - mse: 576.4191 - val_loss: 16.5147 - val_mae: 16.4402 - val_mse: 515.0837 - learning_rate: 5.0000e-04
Epoch 4/200
646/647 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 17.0560 - mae: 16.9861 - mse: 532.4623

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

647/647 ━━━━━━━━━━━━━━━━━━━━ 21s 33ms/step - loss: 17.0552 - mae: 16.9853 - mse: 532.4174 - val_loss: 14.7019 - val_mae: 14.6576 - val_mse: 458.2019 - learning_rate: 5.0000e-04
Epoch 5/200
647/647 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 16.2011 - mae: 16.1603 - mse: 484.7568

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

647/647 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - loss: 16.2009 - mae: 16.1600 - mse: 484.7416 - val_loss: 13.5415 - val_mae: 13.5164 - val_mse: 390.9541 - learning_rate: 5.0000e-04
Epoch 6/200
647/647 ━━━━━━━━━━━━━━━━━━━━ 21s 32ms/step - loss: 15.4120 - mae: 15.3900 - mse: 436.6396 - val_loss: 13.6321 - val_mae: 13.6205 - val_mse: 384.5920 - learning_rate: 5.0000e-04
Epoch 7/200
647/647 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 14.8634 - mae: 14.8521 - mse: 414.1678

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

647/647 ━━━━━━━━━━━━━━━━━━━━ 23s 36ms/step - loss: 14.8634 - mae: 14.8521 - mse: 414.1667 - val_loss: 12.3444 - val_mae: 12.3421 - val_mse: 358.9181 - learning_rate: 5.0000e-04
Epoch 8/200
647/647 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - loss: 14.3669 - mae: 14.3634 - mse: 383.1433 - val_loss: 13.2289 - val_mae: 13.2314 - val_mse: 368.2870 - learning_rate: 5.0000e-04
Epoch 9/200
647/647 ━━━━━━━━━━━━━━━━━━━━ 21s 32ms/step - loss: 14.0172 - mae: 14.0179 - mse: 371.5515 - val_loss: 14.2787 - val_mae: 14.2860 - val_mse: 414.4207 - learning_rate: 5.0000e-04
Epoch 10/200
647/647 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - loss: 13.3745 - mae: 13.3779 - mse: 335.6632 - val_loss: 12.6730 - val_mae: 12.6785 - val_mse: 357.5479 - learning_rate: 5.0000e-04
Epoch 11/200
647/647 ━━━━━━━━━━━━━━━━━━━━ 21s 32ms/step - loss: 13.0806 - mae: 13.0823 - mse: 318.1779 - val_loss: 13.2681 - val_mae: 13.2687 - val_mse: 382.4723 - learning_rate: 5.0000e-04
Epoch 12/200
646/647 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 12.4937 - mae: 12.4891 - mse: 295.0853

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

647/647 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - loss: 12.4936 - mae: 12.4890 - mse: 295.0843 - val_loss: 12.0203 - val_mae: 12.0152 - val_mse: 381.6892 - learning_rate: 5.0000e-04
Epoch 13/200
647/647 ━━━━━━━━━━━━━━━━━━━━ 21s 32ms/step - loss: 12.5038 - mae: 12.4938 - mse: 293.8611 - val_loss: 12.4433 - val_mae: 12.4217 - val_mse: 383.4427 - learning_rate: 5.0000e-04
Epoch 14/200
647/647 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - loss: 12.0348 - mae: 12.0164 - mse: 275.2196 - val_loss: 13.5684 - val_mae: 13.5478 - val_mse: 406.4919 - learning_rate: 5.0000e-04
Epoch 15/200
647/647 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - loss: 11.6044 - mae: 11.5785 - mse: 252.3595 - val_loss: 12.0695 - val_mae: 12.0368 - val_mse: 362.6602 - learning_rate: 5.0000e-04
Epoch 16/200
647/647 ━━━━━━━━━━━━━━━━━━━━ 42s 35ms/step - loss: 11.2650 - mae: 11.2285 - mse: 237.9103 - val_loss: 14.1749 - val_mae: 14.1377 - val_mse: 384.5380 - learning_rate: 5.0000e-04
Epoch 17/200
647/647 ━━━━━━━━━━━━━━━━━━━━ 21s 33ms/step - loss: 11.0701 - mae: 11.0253 - mse: 227.8213 - val_loss: 13.2021 - val_mae: 13.1586 - val_mse: 386.4623 - learning_rate: 5.0000e-04
Epoch 18/200
647/647 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - loss: 10.8515 - mae: 10.8029 - mse: 215.2001 - val_loss: 13.2300 - val_mae: 13.1812 - val_mse: 383.5021 - learning_rate: 5.0000e-04
Epoch 19/200
647/647 ━━━━━━━━━━━━━━━━━━━━ 21s 32ms/step - loss: 10.4956 - mae: 10.4382 - mse: 203.8248 - val_loss: 12.9049 - val_mae: 12.8496 - val_mse: 408.8633 - learning_rate: 5.0000e-04
Epoch 20/200
647/647 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - loss: 10.4464 - mae: 10.3831 - mse: 199.1457 - val_loss: 13.7553 - val_mae: 13.6942 - val_mse: 407.1942 - learning_rate: 5.0000e-04
Epoch 21/200
647/647 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - loss: 10.1588 - mae: 10.0892 - mse: 191.4091 - val_loss: 13.3670 - val_mae: 13.3000 - val_mse: 388.7846 - learning_rate: 5.0000e-04
Epoch 22/200
647/647 ━━━━━━━━━━━━━━━━━━━━ 41s 34ms/step - loss: 9.9582 - mae: 9.8828 - mse: 184.3016 - val_loss: 12.7658 - val_mae: 12.6938 - val_mse: 388.0408 - learning_rate: 5.0000e-04
Epoch 23/200
647/647 ━━━━━━━━━━━━━━━━━━━━ 21s 32ms/step - loss: 9.3754 - mae: 9.2983 - mse: 161.2227 - val_loss: 13.1282 - val_mae: 13.0640 - val_mse: 391.2410 - learning_rate: 2.5000e-04
Epoch 24/200
647/647 ━━━━━━━━━━━━━━━━━━━━ 22s 35ms/step - loss: 9.1264 - mae: 9.0558 - mse: 153.8395 - val_loss: 12.8098 - val_mae: 12.7458 - val_mse: 386.4665 - learning_rate: 2.5000e-04
Epoch 25/200
647/647 ━━━━━━━━━━━━━━━━━━━━ 21s 32ms/step - loss: 8.9774 - mae: 8.9132 - mse: 147.7620 - val_loss: 13.1574 - val_mae: 13.1068 - val_mse: 393.5129 - learning_rate: 2.5000e-04
Epoch 26/200
647/647 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - loss: 8.7783 - mae: 8.7192 - mse: 141.7123 - val_loss: 12.6183 - val_mae: 12.5718 - val_mse: 392.5234 - learning_rate: 2.5000e-04
Epoch 27/200
647/647 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - loss: 8.7218 - mae: 8.6676 - mse: 140.8139 - val_loss: 12.5745 - val_mae: 12.5040 - val_mse: 400.3774 - learning_rate: 2.5000e-04
Epoch 28/200
647/647 ━━━━━━━━━━━━━━━━━━━━ 22s 33ms/step - loss: 8.6899 - mae: 8.6377 - mse: 138.7827 - val_loss: 12.9211 - val_mae: 12.8828 - val_mse: 375.4283 - learning_rate: 2.5000e-04
Epoch 29/200
647/647 ━━━━━━━━━━━━━━━━━━━━ 23s 35ms/step - loss: 8.4462 - mae: 8.4012 - mse: 130.6165 - val_loss: 13.1135 - val_mae: 13.0812 - val_mse: 390.9432 - learning_rate: 2.5000e-04
Epoch 30/200
647/647 ━━━━━━━━━━━━━━━━━━━━ 22s 33ms/step - loss: 8.3545 - mae: 8.3116 - mse: 127.6665 - val_loss: 13.1919 - val_mae: 13.1541 - val_mse: 415.2102 - learning_rate: 2.5000e-04
Epoch 31/200
647/647 ━━━━━━━━━━━━━━━━━━━━ 22s 35ms/step - loss: 8.2539 - mae: 8.2140 - mse: 125.2637 - val_loss: 12.8209 - val_mae: 12.7887 - val_mse: 389.9010 - learning_rate: 2.5000e-04
Epoch 32/200
647/647 ━━━━━━━━━━━━━━━━━━━━ 23s 36ms/step - loss: 8.3713 - mae: 8.3348 - mse: 130.1204 - val_loss: 13.3401 - val_mae: 13.3164 - val_mse: 402.7003 - learning_rate: 2.5000e-04
Epoch 33/200
647/647 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - loss: 7.9808 - mae: 7.9471 - mse: 115.8502 - val_loss: 12.8036 - val_mae: 12.7832 - val_mse: 379.0214 - learning_rate: 1.2500e-04
Epoch 34/200
647/647 ━━━━━━━━━━━━━━━━━━━━ 22s 35ms/step - loss: 8.0202 - mae: 7.9903 - mse: 119.5632 - val_loss: 13.0393 - val_mae: 13.0242 - val_mse: 394.1268 - learning_rate: 1.2500e-04
Epoch 35/200
647/647 ━━━━━━━━━━━━━━━━━━━━ 21s 33ms/step - loss: 7.9716 - mae: 7.9465 - mse: 116.1102 - val_loss: 12.7645 - val_mae: 12.7469 - val_mse: 390.7462 - learning_rate: 1.2500e-04
Epoch 36/200
647/647 ━━━━━━━━━━━━━━━━━━━━ 23s 35ms/step - loss: 7.9419 - mae: 7.9209 - mse: 115.3769 - val_loss: 13.4294 - val_mae: 13.4218 - val_mse: 393.4279 - learning_rate: 1.2500e-04
Epoch 37/200
647/647 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - loss: 7.9002 - mae: 7.8827 - mse: 113.8979 - val_loss: 13.1398 - val_mae: 13.1343 - val_mse: 395.8354 - learning_rate: 1.2500e-04
Epoch 38/200
647/647 ━━━━━━━━━━━━━━━━━━━━ 42s 35ms/step - loss: 7.8354 - mae: 7.8197 - mse: 114.2458 - val_loss: 13.2637 - val_mae: 13.2624 - val_mse: 402.2930 - learning_rate: 1.2500e-04
Epoch 39/200
647/647 ━━━━━━━━━━━━━━━━━━━━ 21s 33ms/step - loss: 7.8871 - mae: 7.8757 - mse: 114.6543 - val_loss: 12.7270 - val_mae: 12.7205 - val_mse: 393.6994 - learning_rate: 1.2500e-04
Epoch 40/200
647/647 ━━━━━━━━━━━━━━━━━━━━ 22s 35ms/step - loss: 7.7703 - mae: 7.7621 - mse: 111.3019 - val_loss: 13.4460 - val_mae: 13.4507 - val_mse: 420.9021 - learning_rate: 1.2500e-04
Epoch 41/200
647/647 ━━━━━━━━━━━━━━━━━━━━ 22s 33ms/step - loss: 7.7670 - mae: 7.7616 - mse: 110.9005 - val_loss: 13.5093 - val_mae: 13.5174 - val_mse: 407.9878 - learning_rate: 1.2500e-04
Epoch 42/200
647/647 ━━━━━━━━━━━━━━━━━━━━ 22s 35ms/step - loss: 7.7417 - mae: 7.7385 - mse: 111.5930 - val_loss: 13.1928 - val_mae: 13.1995 - val_mse: 401.0583 - learning_rate: 1.2500e-04
Epoch 43/200
647/647 ━━━━━━━━━━━━━━━━━━━━ 22s 35ms/step - loss: 7.6814 - mae: 7.6833 - mse: 108.0554 - val_loss: 13.2419 - val_mae: 13.2554 - val_mse: 404.9358 - learning_rate: 6.2500e-05
Epoch 44/200
647/647 ━━━━━━━━━━━━━━━━━━━━ 23s 35ms/step - loss: 7.4821 - mae: 7.4839 - mse: 104.3360 - val_loss: 13.1164 - val_mae: 13.1318 - val_mse: 404.2735 - learning_rate: 6.2500e-05
Epoch 45/200
647/647 ━━━━━━━━━━━━━━━━━━━━ 23s 35ms/step - loss: 7.6003 - mae: 7.6038 - mse: 107.7095 - val_loss: 12.9986 - val_mae: 13.0127 - val_mse: 401.7241 - learning_rate: 6.2500e-05
Epoch 46/200
647/647 ━━━━━━━━━━━━━━━━━━━━ 22s 35ms/step - loss: 7.4611 - mae: 7.4658 - mse: 103.4589 - val_loss: 13.1807 - val_mae: 13.1941 - val_mse: 417.1322 - learning_rate: 6.2500e-05
Epoch 47/200
647/647 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - loss: 7.6361 - mae: 7.6450 - mse: 107.1328 - val_loss: 13.2768 - val_mae: 13.2985 - val_mse: 395.0392 - learning_rate: 6.2500e-05
Fold 5 Results -> MAE: 12.0152, RMSE: 19.5369, R²: 0.7801

=== Cross-Validation Summary ===
MAE: 12.4177, RMSE: 19.0250, R²: 0.7894

Best Fold: 3

✅ Optimized Test Results:
  MAE:  19.1453
  RMSE: 27.2563
  R²:   0.7325